<style>
            table{
                border-collapse:collapse;

            }

            td{
              padding-left:5px;
              padding-right:5px;  
            }

            th{
              text-wrap: wrap;
              font-size:9px;
              padding-left:5px;
              padding-right:5px;  
            }

            .text-center{
                text-align: center !important;
                padding-left: auto;
                padding-right:auto;
            }

            

            #main{
                font-size:9px;
            }

            .bg-contract-item{
                background-color: #d3d3d3;
            }

            .bg-excluded-sum-component_item{
                background-color: #fffec8;
            }

            .bg-excluded-sum-component{
                background-color: #ADD8E6;
            }


            .font-color-danger{
                color: #ff0000;
            }
        </style>
    
<page id="main">
            

    <page_footer>
        <br>
        <table class="page_footer">
            <tr>
                <td style="width: 50%;font-size:12px;">
                    <strong>Material Budget:</strong> {{$project->name}} - {{$section->name}} - {{$current_datetime}}
                </td>
                <td style="width: 50%; text-align: right;font-size:12px">
                    [[page_cu]] / [[page_nb]]
                </td>
            </tr>
        </table>
    </page_footer>
        @php
            function formatFactor($factor){
                
                $factor_arr = explode('.',$factor);
                
                if($factor_arr[1] == '000000'){
                    return $factor_arr[0].'.00';
                }
                
                return $factor_arr[0].'.'.rtrim($factor_arr[1],'0');
            }
        @endphp

        <table border="1">
            <tr>
                <td colspan="2" style="text-align:center">
                    <img src="storage/sys_images/header.png" style="width:500px"/>
                </td>
                <td colspan="2" style="text-align:center" valign="middle">
                    <h2>Material Budget</h2>
                </td>
            </tr>
            <tr>
                <th style="width:15%;text-align:center">
                    Project
                </th>
                <td style="width:35%">
                    {{$project->name}}
                </td>
            
                <th style="width:15%;text-align:center">
                    Date & Time Generated
                </th>
                <td style="width:35%">
                    {{$current_datetime}}
                </td>
            </tr>
            <tr>
                <th style="text-align:center">
                    Section
                </th>
                <td>
                    {{$section->name}}
                </td>
            
                <th style="text-align:center">
                    Generated By
                </th>
                <td>
                    {{$current_user->name}}
                </td>
            </tr>
        </table>
        <br>
        <table>
            <tr>
                <td>
                    Color legend: 
                    <br>  
                    <div>
                        <span style="margin-left:10px;background-color:#add8e6;border:solid 1px #000000">__</span> - A component is excluded from sumation due to incompatible unit or the item was explicitly flagged by user.  
                        <span style="margin-left:10px;background-color:#fffec8;border:solid 1px #000000">__</span> - An item is excluded from sumation due to incompatible unit or the item was explicitly flagged by user.
                    
                        <span style="margin-left:10px;background-color:#ff0000;border:solid 1px #000000">__</span> - Red font indicates that the total is over budget.  
                        <span style="margin-left:10px;background-color:#d3d3d3;border:solid 1px #000000">__</span> - Contract Item or grand total.
                     </div>  
                     <br>
                </td>
            </tr>
        </table>


        <div>
        <table border="1">
          
            <tr>
                <th rowspan="2" style="text-align:center">Item Code</th>
                <th style="text-align:center;" rowspan="2">Description</th>
                <th style="text-align:center" colspan="4">Contract</th>
                <th style="text-align:center" colspan="4">POW/DUPA</th>
                <th style="text-align:center">Factor</th>
                <th style="text-align:center" colspan="4">Material Budget</th>
            </tr>
            <tr>
                <th style="text-align:center">QTY</th>
                <th style="text-align:center">UNIT</th>
                <th style="text-align:center">PRICE</th>
                <th style="text-align:center">AMOUNT</th>
                <th style="text-align:center">QTY</th>
                <th style="text-align:center">UNIT</th>
                <th style="text-align:center">RATE</th>
                <th style="text-align:center">AMOUNT</th>
                <th style="text-align:center">QTY / UNIT</th>
                <th style="text-align:center">QTY</th>
                <th style="text-align:center">UNIT</th>
                <th style="text-align:center">COST</th>
                <th style="text-align:center">AMOUNT</th>
            </tr>

          
        </table>
        </div>           
        
</page>